# 错误边界

## 含义

+ 默认情况下，若一个组件在**渲染**期间（ `render` ）发生错误，会导致整个组件全部被卸载

+ 错误边界：是一个组件，该组件会捕获到渲染期间（`render`）子组件发生的错误，并有能力阻止错误继续传递

## 细节

+ 某些错误，错误边界无法捕获

  + 组件自身错误

  + 异步错误

  + 事件中的错误

+ 总结：仅仅处理渲染子组件期间的同步错误

## 捕获错误

1. 方法1：编写生命周期函数 `static getDerivedStateFromError(err)`

2. 方法2：编写生命周期函数 `componentDidCatch(error, info)`

## static getDerivedStateFromError(error)

+ 静态函数。函数内不能使用 this

+ 运行时间点：渲染子组件的过程中，发生错误之后，在更新页面**之前**

+ 只有**子组件**发生**错误**，才会运行该函数

+ 该函数返回一个对象， React 会将该对象的属性覆盖掉当前组件的 `state`

+ 参数

  + `error`-错误对象

    ```jsx
    import React, { Component } from 'react'

    export default class Con extends Component {

      constructor(props) {
        super(props)
        this.state = {
          err: false
        }
      }

      static getDerivedStateFromError(err) {
        console.log('子组件出现错误了');
        console.log(err);
        return {
          err: true
        }
      }

      render() {

        if(this.state.err) {
          return <p>组件出现错误，渣渣</p>
        }

        return (
          <div>
            正常显示
            { this.props.children }
          </div>
        )
      }
    }
    ```

## componentDidCatch(error, info)

+ 实例方法

+ 渲染子组件的过程中，发生错误，更新页面**之后**

+ 由于运行时间点比较靠后，因此不太会在该函数中改变状态

+ 参数

  + `error`: 错误对象

  + `info`：错误摘要信息

+ **通常用于记录错误消息**

  + 代码

      ```jsx
      import React, { Component } from 'react'

      export default class Con extends Component {

        constructor(props) {
          super(props)
          this.state = {
            err: false
          }
        }

        // 处理
        componentDidCatch(error, info) {
          this.setState(() => {
            return {
              err: true
            }
          })
        }

        render() {

          if(this.state.err) {
            return <p>组件出现错误，渣渣</p>
          }

          return (
            <div>
              正常显示
              { this.props.children }
            </div>
          )
        }
      }
      ```
